version: "3.4"

services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    volumes:
      - ./app:/app
      - data_volume:/var/lib/mysql

  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_PORT}:80
    restart: always
    volumes:
      - ./app:/app
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build: 
      args:
        php_deps: ${PHP_DEPS}
        php_extensions: ${PHP_EXTENSIONS}
        php_version: ${PHP_VERSION}
      context: .
      dockerfile: Dockerfile-php
    restart: always
    volumes:
      - ./app:/app

volumes:
  data_volume: {}

